######################################################################################################
############################## Generic secret into env variable ###################################### 
######################################################################################################

apiVersion: v1
kind: Namespace
metadata:
  name: testing-secrets
---
apiVersion: v1
kind: Secret
metadata: 
  name: env-secrets
  namespace: testing-secrets
data:
  random-variable: "c29tZS1lbnYtdmFyaWFibGUK"               # generic secrets in kubernetes in this form, works only as base64 encoded string 
  some-variable: "c29tZS1tb3JlLWVudi12YXJpYWJsZS12YWx1ZQo=" # generic secrets in kubernetes in this form, works only as base64 encoded string
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deplo
  namespace: testing-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deplo
  template:
    metadata:
      labels:
        app: my-deplo
    spec:
      containers:
      - image: alpine:3.24.1
        name: alpine
        env:
        - name: key-for-env-variable # as name, that name will end up in env file as its name.
          valueFrom: 
            secretKeyRef:
              key: some-variable  # reference to key in secret from which value will be injected into env variable.
              name: env-secrets   # secret obj name

        - name: key-for-env-variable-2 # as name, that name will end up in env file as its name.
          valueFrom:
            secretKeyRef:
              key: random-variable # reference to key in secret from which value will be injected into env variable.
              name: env-secrets    # # secret obj name 
        
        command: ["sleep", "infinite"]
