apiVersion: v1
kind: Namespace
metadata:
  name: testing-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-secrets
  namespace: testing-secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: namespaced-store
  namespace: testing-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local.:8200"
      path: "secret"
      version: "v2"
      auth: 
        kubernetes:
          mountPath: "kubernetes"
          role: "testing-role"
          serviceAccountRef:
            name: read-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-reaching
  namespace: testing-secrets
spec:
  refreshInterval: "1h"
  refreshPolicy: OnChange
  secretStoreRef: 
    kind: SecretStore
    name: namespaced-store
  target:
    creationPolicy: Owner
    immutable: false
    name: my-secret
    
  data:
    - secretKey: first-secret
      remoteRef: 
        key: "test/testing"
        property: first
    
    - secretKey: second-secret 
      remoteRef:
        key: "test/testing"
        property: second
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: testing-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alp
  template:
    metadata:
      labels:
        app: alp
    spec:
      containers:
      - name: alpine-linux
        image: alpine:3.24.1
        imagePullPolicy: IfNotPresent
        command:
        - "sleep"
        - "infinity"
        ports:
        - containerPort: 2000
          protocol: TCP 
