apiVersion: v1
kind: Namespace
metadata:
  name: testing-cmaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: testing-cmaps
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    http {
      server { 
        listen 80;
        location / {
          root /usr/share/nginx/html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: testing-cmaps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
        - name: nginx-cfg
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-cfg
        configMap: 
          name: nginx-config