#####################################################################################################
####################### injecting secrets into pods with the help of ESO ############################
######################## i used hashicorp vault as provider for secret ##############################
#####################################################################################################

# namespace and serviceAccount together with apropriate role and policy set up in vault is nessesery
# to pull it of. 

apiVersion: v1
kind: Namespace
metadata:
  name: testing-es
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-secrets
  namespace: testing-es
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets
  namespace: testing-es
spec:
  secretStoreRef:
    kind: SecretStore
    name: from-vault
  data:
  - remoteRef: 
      key: testing
      property: secret1
    secretKey: first-secret-object
  - remoteRef: 
      key: testing
      property: secret2
    secretKey: second-secret-object 
  refreshPolicy: OnChange
  target:
    name: secret-objects-name
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: from-vault
  namespace: testing-es
spec: 
  provider:    
    vault:
      auth:
        kubernetes:
          role: "learning-eso-role" 
          mountPath: "kubernetes"
          serviceAccountRef:
            name: read-secrets
      path: "secret"
      version: "v2"
      server: "http://vault.vault.svc:8200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: testing-es
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: alpi
  template:
    metadata: 
      labels: 
        apps: alpi
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep","infinity"]
        env:
        - name: first-env
          valueFrom:
            secretKeyRef:
              name: secret-objects-name
              key: first-secret-object
        - name: second-env
          valueFrom: 
            secretKeyRef:
              name: secret-objects-name
              key: second-secret-object