########################################################################################
####### Generic dot-file secret mounted as volume into pod #############################
########################################################################################

apiVersion: v1
kind: Namespace
metadata:
    name: testing-secrets
---
apiVersion: v1
kind: Secret
metadata:
    name: dotfile-secret
    namespace: testing-secrets
data:
    .secret-file: YWRtaW4K # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: alpine-test
    namespace: testing-secrets
spec:
    replicas: 1
    selector: 
        matchLabels:
            apps: alpi

    template:
        metadata:
            labels:
                apps: alpi
        spec:
            containers:
            -   name: alipne-test
                image: alpine:3.24.1
                command: ["sleep", "infinity"]
                volumeMounts:
                -   name: secret-volume
                    readOnly: true
                    mountPath: "/etc/secret-volume"
            
            volumes:
            -   name: secret-volume
                secret:
                    secretName: dotfile-secret
